import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Card from "./_componnent/card";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={{
          width: "100%",
          background: "teal",
          fontSize: "30px",
          height: '50px',
          display: 'flex',
          justifyContent: "center",
          alignItems: 'center',
        }}>
          <Link href='/articels' className="link">articels</Link>
          <Link href='/' className="link">Home</Link>
          <Link href='/post' className="link">Post</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
